.\" Manpage for ccat
.\" Contact vh8t
.TH CCAT 1 "April 2024" "1.0" "ccat man page"

.SH NAME
ccat \- display contents of a file with syntax highlighting

.SH SYNOPSIS
.B ccat
[\fIflags\fR] [\fIfile\fR]

.SH DESCRIPTION
Display the contents of the specified \fIfile\fR with syntax highlighting.

.SH POSITIONAL ARGUMENTS
.TP
\fBfile\fR
The file path to display contents of.

.SH OPTIONS
.TP
\fB\-e, \-\-show-ends\fR
Display $ at the end of each line.

.TP
\fB\-n, \-\-number\fR
Number all output lines.

.TP
\fB\-s, \-\-squeeze-blank\fR
Suppress repeated empty output lines.

.TP
\fB\-t, \-\-show-tabs\fR
Display TAB characters as ^I.

.SH COPYRIGHT
This command is part of the SuperUtils collection (ccat - colorful cat).
Copyright (C) 2024 vh8t.

.SH AUTHOR
vh8t
GitHub: https://github.com/vh8t
Website: https://vh8t.xyz
