.\" Manpage for sls
.\" Contact vh8t
.TH SLS 1 "April 2024" "1.0" "sls man page"

.SH NAME
sls \- list information about files

.SH SYNOPSIS
.B sls
[\fIflags\fR] [\fIfile\fR]

.SH DESCRIPTION
List information about the specified \fIfile\fR (the current directory by default).

.SH POSITIONAL ARGUMENTS
.TP
\fBfile\fR
The directory or file path to list information about (default: current directory).

.SH OPTIONS
.TP
\fB\-a, \-\-all\fR
Show all files, including hidden files.

.TP
\fB\-h, \-\-human-readable\fR
Print file sizes in human-readable format.

.SH COPYRIGHT
This command is part of the SuperUtils collection (sls - super ls).
Copyright (C) 2024 vh8t.

.SH AUTHOR
vh8t
GitHub: https://github.com/vh8t
Website: https://vh8t.xyz
